[pytest]
addopts = -p no:cacheprovider -n auto --dist worksteal --import-mode=importlib
testpaths = tests
norecursedirs = .git .pytest_cache .pytest_tmp .tmp_pip .tmp_tests .runtime __pycache__ backing_storage
python_files = test_*.py
